name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Learning Github Workflows :)"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python Commands
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-win-commands:
    runs-on: windows-latest
    steps:
      - name: print dir in powershell
        run: Get-Location
      - name: print dir bash
        run: pwd
        shell: bash